"""
soma/viz/plots.py
==================
Matplotlib plot generation for SOMA evaluation outputs.

All plots saved to results/. Generated by training scripts, not the demo server.
The demo server uses the React frontend (D3/Recharts) for live visualisation.

Hero visual: plot_convergence() — RL vs PBE convergence across 3 κ values.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from pathlib import Path
from typing import Optional


# SOMA color system (matches CSS vars in frontend)
COLORS = {
    "rl":          "#22d3ee",   # cyan  — learned RL policy
    "pbe":         "#a855f7",   # purple — PBE benchmark
    "healthy":     "#22d3ee",
    "compromised": "#ef4444",
    "honeypot":    "#f59e0b",
    "muted":       "#64748b",
}
BG     = "#0a0e1a"
SURFACE= "#111827"


def _apply_dark_theme(fig, axes):
    fig.patch.set_facecolor(BG)
    for ax in (axes if hasattr(axes, '__iter__') else [axes]):
        ax.set_facecolor(SURFACE)
        ax.tick_params(colors=COLORS["muted"])
        ax.xaxis.label.set_color(COLORS["muted"])
        ax.yaxis.label.set_color(COLORS["muted"])
        ax.title.set_color("#e2e8f0")
        for spine in ax.spines.values():
            spine.set_color(COLORS["muted"])


def plot_convergence(
    convergence_data: dict,
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """
    Hero visual: RL mixing rate r (cyan) converging toward PBE r* (purple)
    across 3 κ values.

    Parameters
    ----------
    convergence_data : dict
        {kappa: {"learned_r_history": [float,...], "pbe_r_star": float}}
        learned_r_history: r measured at each evaluation checkpoint
    save_path : Path, optional
    """
    kappas = sorted(convergence_data.keys())
    fig, axes = plt.subplots(1, len(kappas), figsize=(14, 4))
    fig.suptitle(
        "Layer 3: RL Convergence to PBE Equilibrium\n"
        "Cyan = learned RL policy  ·  Purple = game-theoretic PBE benchmark",
        color="#e2e8f0", fontsize=11,
    )
    _apply_dark_theme(fig, axes)

    for ax, kappa in zip(axes, kappas):
        d       = convergence_data[kappa]
        history = d.get("learned_r_history", [])
        pbe_r   = d.get("pbe_r_star", 0.0)
        steps   = np.linspace(0, 100_000, len(history))

        ax.plot(steps, history, color=COLORS["rl"],  lw=2, label="Learned r")
        ax.axhline(pbe_r,      color=COLORS["pbe"], lw=2, ls="--", label=f"PBE r*={pbe_r:.3f}")
        ax.set_title(f"κ = {kappa:.1f}", fontsize=10)
        ax.set_xlabel("Training steps")
        ax.set_ylabel("Honeypot baiting rate r")
        ax.set_ylim(0, 1)
        ax.legend(fontsize=8, facecolor=SURFACE, labelcolor="#e2e8f0")
        ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{x/1000:.0f}k"))

    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=BG)
        print(f"Saved: {save_path}")
    return fig


def plot_kappa_sweep(
    pbe_results: dict,
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """
    Plot optimal honeypot baiting rate r* vs κ (theoretical sweep).
    Shows monotone increasing relationship — more inattentive attacker → more bait.
    """
    kappas  = sorted(pbe_results.keys())
    r_stars = [pbe_results[k].r_star  for k in kappas]
    mu_stars= [pbe_results[k].mu_star for k in kappas]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
    fig.suptitle("Theoretical κ Sweep — PBE Equilibrium vs Attacker Attention Cost",
                 color="#e2e8f0")
    _apply_dark_theme(fig, [ax1, ax2])

    ax1.plot(kappas, r_stars,  color=COLORS["pbe"], lw=2, marker="o")
    ax1.set_xlabel("κ (attention cost)")
    ax1.set_ylabel("r* (optimal honeypot baiting rate)")
    ax1.set_title("More inattentive → more bait")

    ax2.plot(kappas, mu_stars, color=COLORS["rl"],  lw=2, marker="o")
    ax2.set_xlabel("κ (attention cost)")
    ax2.set_ylabel("μ* (attack threshold)")
    ax2.set_title("More inattentive → higher threshold to attack")

    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=BG)
    return fig


def plot_detection_rates(
    metrics: dict,
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """Bar chart of per-chain-step detection rates with threshold lines."""
    phases = list(metrics.keys())
    rates  = [metrics[p]["rate"] for p in phases]
    thresholds = {"lateral_movement": 0.50, "impact": 0.80}

    fig, ax = plt.subplots(figsize=(8, 4))
    _apply_dark_theme(fig, ax)

    bars = ax.bar(phases, rates, color=COLORS["healthy"], alpha=0.8)
    for phase, thresh in thresholds.items():
        if phase in phases:
            idx = phases.index(phase)
            ax.axhline(thresh, xmin=(idx)/len(phases), xmax=(idx+1)/len(phases),
                       color=COLORS["compromised"], ls="--", lw=1.5)

    ax.set_ylim(0, 1)
    ax.set_ylabel("Detection rate")
    ax.set_title("Layer 2: Per-Step Detection Rates (dashed = minimum threshold)")
    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=BG)
    return fig
