FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 \
    python3-pip \
    iproute2 \
    procps \
    net-tools \
    curl \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir websockets

RUN useradd -m -s /bin/bash soma && echo 'soma:soma123' | chpasswd
RUN mkdir -p /run/sshd

COPY configs/sshd_config /etc/ssh/sshd_config
COPY soma_agent.py /soma_agent.py
COPY fake_data/enterprise1/redis_seed.sh /redis_seed.sh
RUN chmod +x /redis_seed.sh
COPY dockerfiles/entrypoint_enterprise1.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22 6379
CMD ["/entrypoint.sh"]
