"""
scripts/demo.py
================
WebSocket demo server — streams a live CAGE 2 episode to the React frontend.

Serves on ws://localhost:8765
Frontend connects at http://localhost:3000

Fallback: run with --static to export a pre-recorded episode as JSON.
The static fallback must be prepared and tested before the pitch.
CybORG has known install-time stability issues — always have the fallback ready.

Architecture
------------
  CybORGWrapper episode → Layer 1 scores (Isolation Forest)
  → Layer 2 PPO defender actions
  → Layer 3 heuristic honeypot trigger  (NOT the signaling game policy —
    B_lineAgent ignores signals; labeled clearly in the payload)
  → Layer 4 long-dwell drift detection
  → JSON payload → WebSocket → React frontend

Pitch note
----------
The convergence panel (signaling game / PBE) is pre-generated by
train_deception.py and served as a static image. It is not part of
the live stream — it is the hero visual in the frontend, separate panel.
"""

import asyncio
import json
import argparse
import numpy as np
from pathlib import Path

MODELS_DIR  = Path("models")
RESULTS_DIR = Path("results")


# ---------------------------------------------------------------------------
# Per-step observation decomposition
# ---------------------------------------------------------------------------

def split_obs_per_host(obs: np.ndarray) -> dict:
    """Split flat 30-d obs vector into per-host 5-d vectors."""
    from soma.envs.cyborg_wrapper import HOST_NAMES, FEATURES_PER_HOST
    return {
        h: obs[i * FEATURES_PER_HOST: (i + 1) * FEATURES_PER_HOST]
        for i, h in enumerate(HOST_NAMES)
    }


# ---------------------------------------------------------------------------
# Model loader (lazy — called once per WebSocket connection)
# ---------------------------------------------------------------------------

def load_models():
    from soma.layers.innate    import InnateImmunityLayer
    from soma.layers.adaptive  import load as load_ppo
    from soma.layers.suppressor import LongDwellDetector

    innate_path = MODELS_DIR / "innate" / "isolation_forest.joblib"
    ppo_path    = MODELS_DIR / "adaptive" / "soma_ppo_final"
    drift_path  = MODELS_DIR / "innate"  / "drift_detector.joblib"

    if not innate_path.exists():
        raise FileNotFoundError(
            f"{innate_path} not found. Run: python scripts/train_innate.py"
        )
    if not (ppo_path.with_suffix(".zip")).exists():
        raise FileNotFoundError(
            f"{ppo_path}.zip not found. Run: python scripts/train_adaptive.py"
        )

    innate  = InnateImmunityLayer.load(innate_path)
    ppo     = load_ppo(str(ppo_path))

    if drift_path.exists():
        detector = LongDwellDetector.load(drift_path)
    else:
        # Uncalibrated detector — drift_alarm() will return False until calibrated.
        # In the demo this is acceptable; the centroid trajectory is still visualised.
        detector = LongDwellDetector()

    return innate, ppo, detector


# ---------------------------------------------------------------------------
# Episode runner (shared by live and static paths)
# ---------------------------------------------------------------------------

def run_episode_steps(innate, ppo, detector, n_steps: int = 200):
    """
    Generator — yields one payload dict per step.
    Caller decides whether to send over WebSocket or collect for JSON.
    """
    import math
    from soma.envs.cyborg_wrapper          import CybORGWrapper, HOST_NAMES
    from soma.layers.deception             import heuristic_honeypot_trigger
    from soma.fusion.network_correlator    import NetworkImmuneCorrelator
    from soma.fusion.response_orchestrator import ResponseOrchestrator

    env    = CybORGWrapper(include_red=True)
    obs, _ = env.reset()

    correlator   = NetworkImmuneCorrelator()
    orchestrator = ResponseOrchestrator()

    for step in range(n_steps):
        action, _                  = ppo.predict(obs, deterministic=True)
        obs, reward, done, _, info = env.step(int(action))

        obs_per_host = split_obs_per_host(obs)

        # Layer 1 — anomaly detection
        innate_fired   = innate.is_anomalous(obs)
        anomaly_scores = innate.per_host_scores(obs)   # {host: float}

        # Layer 3 — heuristic honeypot trigger (NOT game-theoretic policy)
        honeypot_flags = {
            h: bool(heuristic_honeypot_trigger(anomaly_scores[h]))
            for h in HOST_NAMES
        }

        # Layer 4 — long-dwell drift
        detector.update_all(obs_per_host)
        drift_alarms = {}
        centroid_pos = {}
        for h in HOST_NAMES:
            try:
                drift_alarms[h] = bool(detector.drift_alarm(h))
            except RuntimeError:
                drift_alarms[h] = False   # not yet calibrated — normal for first episode
            traj = detector.centroid_trajectory(h)
            centroid_pos[h] = traj[-1].tolist() if traj else None

        # Fusion — correlate all layer signals into ranked Incidents
        memory_scores = {
            h: math.sqrt(centroid_pos[h][0] ** 2 + centroid_pos[h][1] ** 2)
            if centroid_pos[h] else 0.0
            for h in HOST_NAMES
        }
        incidents = correlator.update_step(
            obs=obs,
            innate_score=max(anomaly_scores.values()) if anomaly_scores else 0.0,
            innate_threshold=float(innate.threshold_),
            memory_scores=memory_scores,
            memory_threshold=1.0,
            tolerance_suppressed=[],
            tolerance_breached=[],
            learned_attack_conf=0.0,
            learned_attack_type="unknown",
            innate_host_scores=anomaly_scores,
        )
        top = correlator.top_threat()

        # Response orchestrator — rule-based recommendation (additive to PPO)
        layer_flags = {
            "innate":   bool(innate_fired),
            "honeypot": any(honeypot_flags.values()),
            "drift":    any(drift_alarms.values()),
            "learned":  False,
        }
        decision = orchestrator.recommend(incidents, layer_flags)

        payload = {
            "step":            step,
            "red_agent_step":  info.get("red_agent_step", step),
            "action":          int(action),
            "reward":          float(reward),

            # Layer 1
            "innate_fired":    bool(innate_fired),
            "anomaly_scores":  {h: float(v) for h, v in anomaly_scores.items()},
            "innate_threshold": float(innate.threshold_),

            # Layer 3 — heuristic, labeled
            "honeypot_flags":  honeypot_flags,
            "honeypot_note":   "heuristic trigger — not the signaling game policy; "
                               "B_lineAgent ignores signals",

            # Layer 4
            "drift_alarms":   drift_alarms,
            "centroid_pos":   centroid_pos,

            # Per-host raw features (for network graph coloring)
            "host_states": {
                h: {
                    "activity":    float(v[0]),
                    "compromised": float(v[1]),
                    "sessions":    float(v[2]),
                    "processes":   float(v[3]),
                }
                for h, v in obs_per_host.items()
            },

            # Fusion incidents
            "incidents": [
                {
                    "host":         inc.host,
                    "score":        inc.score,
                    "layers_fired": inc.layers_fired,
                    "confidence":   inc.confidence,
                    "explanation":  inc.explanation,
                    "attack_type":  inc.attack_type,
                }
                for inc in incidents
            ],
            "top_threat": {"host": top[0], "score": top[1]} if top else None,
            "is_attack":  bool(innate_fired) or any(honeypot_flags.values()),

            # Orchestrator recommendation
            "orchestrator": {
                "recommended_action": decision.recommended_action,
                "action_name":        decision.action_name,
                "host":               decision.host,
                "confidence":         decision.confidence,
                "reason":             decision.reason,
                "incident_score":     decision.incident_score,
            },
        }

        yield payload

        if done:
            break


# ---------------------------------------------------------------------------
# Live WebSocket server
# ---------------------------------------------------------------------------

async def handle_client(websocket):
    """Stream one episode to the connected frontend client."""
    print("  Client connected — starting episode…")
    try:
        innate, ppo, detector = load_models()
        for payload in run_episode_steps(innate, ppo, detector):
            await websocket.send(json.dumps(payload))
            await asyncio.sleep(0.1)
        print("  Episode complete.")
    except Exception as e:
        print(f"  [ERROR] {e}")
        await websocket.send(json.dumps({"error": str(e)}))


async def main_server():
    import websockets
    print("=" * 55)
    print("SOMA demo server  →  ws://localhost:8765")
    print("Open frontend:  cd frontend && npm install && npm start")
    print("=" * 55)
    async with websockets.serve(handle_client, "localhost", 8765):
        await asyncio.Future()   # run forever


# ---------------------------------------------------------------------------
# Static fallback export
# ---------------------------------------------------------------------------

def export_static(
    output_path: Path = Path("results/demo_episode.json"),
    n_steps: int = 200,
):
    """
    Pre-record one episode as JSON for frontend static replay.
    Run this before the pitch and keep the file as a fallback.
    """
    print("Exporting static episode…")
    innate, ppo, detector = load_models()
    steps = list(run_episode_steps(innate, ppo, detector, n_steps=n_steps))

    from soma.envs.cyborg_wrapper import HOST_NAMES
    episode = {
        "meta": {
            "n_steps":         len(steps),
            "host_names":      HOST_NAMES,
            "innate_threshold": float(innate.threshold_),
            "note":            "signaling game convergence panel is separate static image",
        },
        "steps": steps,
    }

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(episode, indent=2))

    n_atk = sum(s["host_states"][HOST_NAMES[0]]["compromised"] > 0 for s in steps)
    n_inn = sum(s["innate_fired"] for s in steps)
    print(f"  Steps: {len(steps)}  |  Innate fired: {n_inn}")
    print(f"  Saved → {output_path}")

    # Copy to frontend public folder if it exists
    dst = Path("frontend/public/demo_episode.json")
    if dst.parent.exists():
        import shutil
        shutil.copy(output_path, dst)
        print(f"  Copied → {dst}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SOMA demo server")
    parser.add_argument(
        "--static", action="store_true",
        help="Export pre-recorded episode JSON instead of running live server"
    )
    parser.add_argument(
        "--out", type=str, default="results/demo_episode.json",
        help="Output path for --static export"
    )
    parser.add_argument(
        "--steps", type=int, default=200,
        help="Episode length for --static export"
    )
    args = parser.parse_args()

    if args.static:
        export_static(output_path=Path(args.out), n_steps=args.steps)
    else:
        asyncio.run(main_server())
